### ISSUE TITLE
Occasional bug when trying to load a font

### ISSUE THREAD

**Issue by vinnydiehl** [FreeFalcon/freefalcon-central#18]
Sometimes [this assertion](https://github.com/FreeFalcon/freefalcon-central/blob/e8698f961fe33b2cccf0d7f8b8e23dcbd2283dff/src/graphics/renderer/render2d.cpp#L1102) fails, sometimes it doesn't. The file that it is trying to read is at `art/ckptart/autofont/16x12font.rct` in the FF install directory. The contents of `str` on the pass where it fails is `"3 43 234 10 18 1\n"`\- only 6 numbers, when there should be 7 or more. It appears to reach the EOF one-off.

I can't exactly pin down the cause of this- it seems to crop up whenever it feels like it, and disappear whenever I try to observe it.

**Comment by PeterMeyer** [comment]
16x12font.rct is an Textfile. As far as i can see the formatstring expects 7 paramas, but in the last line (not the blank line at the end) is only a 6 params. Maybe sometimes it read everything and sometimes not. This might could explain this.Maybe you can simply add and 0 Param  and see whats happend.

**Comment by vinnydiehl** [comment]
The cause of this issue is indeed a malformed font file. Solution: add a `1` param to the end of `art/ckptart/autofont/16x12font.rct` and call it a day. We need a better way to develop on the game content and share changes such as this one rather than word of mouth, so I'll work on a strategy for getting those files under version control.

**Comment by vinnydiehl** [comment]
`art/ckptart/3dfont/16x12font.rct` also has this malformation, add a 1 to the end of that also.
