### ISSUE TITLE
Visual Studio 2010 Migration

### ISSUE THREAD

**Issue by vinnydiehl** [FreeFalcon/freefalcon-central#2]
Issue to track the migration to Visual Studio 2010. Right now #1 is the main roadblock that we face.

**Comment by sthalik** [comment]
What for? Do you need link-time code generation done on multiple cores? This is the only thing 2008 won't do.

I'd rather have the project migrate to the CMake build system. Then it can be used with Qt Creator, CodeBlocks, etc... Having an open-source project use .sln files is a bit unusual.

**Comment by ghost** [comment]
Use the build manual and you will have a working MSVS2013 installation.

**Comment by ghost** [comment]
MSVS2010 is no longer a prerequisite.
We are now using MSVS2013.

**Comment by kinsung** [comment]
can freefalcon-central be built using MSVS2013 and directx9 or directx10?
