### ISSUE TITLE
UI-TacRef no textures

### ISSUE THREAD

**Issue by ghost** [FreeFalcon/freefalcon-central#34]
All weapons are shown as white, without any textures.
Helicopters are shown with a rotating square instead of a rotor.

**Comment by Stewie23** [comment]
i got the textures in tac ref working, but was not shure why, so i never commitet that, changed 

https://github.com/FreeFalcon/freefalcon-central/blob/develop/src/graphics/bsplib/texbank.cpp#L556

to:

TexturePool[id].tex.flags = MPR_TI_DDS;

Also it seems that there are several places in the code that load textures^^

**Comment by ghost** [comment]
Please do.
Thank you very much for your help, it is greatly appreciated.

**Comment by Stewie23** [comment]
yeah im building falcon again at the moment, will probably take some time  - so you might wanna check out if that change solves your problem.

**Comment by ghost** [comment]
https://github.com/FreeFalcon/docs/tree/master/guides
Please use this guide. Your feedback about it will be taken into making it better.

**Comment by ghost** [comment]
https://github.com/dannycoh/docs
Use this build manual as the former one is old.
This one is still waiting to be merged by a pull request.

**Comment by Stewie23** [comment]
allright, yeah anywas waiting for downloads to finish

**Comment by ghost** [comment]
https://github.com/dannycoh/docs/tree/master/guides
Direct link.

**Comment by Stewie23** [comment]
worked, thanks for the guide

**Comment by ghost** [comment]
Any feedback about the build guide that can make it better?

**Comment by Stewie23** [comment]
na it was strait forward, i did not realy get the rational behind having visual studio 2010 and 2013, is it optional ? i anways got 2013. 

I guess it would be usefull to link the coding guides at the end the project has

**Comment by ghost** [comment]
Yes I had the same problem.
I couldn't install MSVS2013 and make the solution compile without installing MSVS2010 first.
If you find a way how to do it, please let me know.
Obviously, you can edit the build manual yourself...

**Comment by PeterMeyer** [comment]
The old Project files where based on Visual Studiob 2003 and was ported by us to Visual Studio 2010 because it was the standard/mainstream ide at this time. It took us days to port it over to VS2010 because there where some very nasty changes on the new compiler generation and we had hundred of Source errors to fix in the first place getting a sane build.Thadts one of the reason the BMS Team and the other ceased (non OpeSource) Falconprojects was developing its versions with Visual Studio 2003 (MSVC 7 ) to. We are the first Team, trying to use more recent compiler and IDE Versions at all.

**Comment by ghost** [comment]
Hello Peter!
Just read your FreeFalcon Wiki pages.
Your contribution is appreciated so please come back and help us with development!

**Comment by ghost** [comment]
Good news!
My last commit solved this.
There is no more need to install MSVS2010.
Also, no need to install the Windows SDK 7.1.
@vinnydiehl please fix the build manual accordingly.

**Comment by ghost** [comment]
The last merge fixed the missing textures.
Thanks Stewie23!
