### ISSUE TITLE
Copyprotection code from former FF Coder 

### ISSUE THREAD

**Issue by PeterMeyer** [FreeFalcon/freefalcon-central#6]
There are  a few lines of code, made by the old Coder Fred Balding (Baldeagle) wich makes
some Copyprotection checks, 

File: F4find.cpp

```
    // FF protection
    static int Done = 0;
    sprintf(path, "%s\\sounds\\files.dir", FalconDataDirectory);
```

Ranger reported me via EMail about this a few month ago.

**Comment by vinnydiehl** [comment]
[Link](https://github.com/FreeFalcon/freefalcon-central/blob/1119f138758cb67e8506e7fb6815c861d8a7c84a/src/falclib/f4find.cpp#L76)

The code looks a bit dated, probably okay to kill it?

**Comment by PeterMeyer** [comment]
Yeah remove it. I hate bs like this.
